package wyyy.bean;

import org.greenrobot.greendao.annotation.*;

import wyyy.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

import wyyy.dao.TaskDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * 任务类，对应数据库中的一张任务表，存储护士的任务列表
 */
@Entity(active = true)
public class Task {

    @Id
    private Long id;
    //病区ID
    private Long BQID;
    //责任护士ID
    private Long USERID;
    //任务类型 :输血；皮试；静滴；静注；化验；其他药�?
    private Integer RWLX;
    //任务�?
    private String RWM;
    //住院�?
    private String ZYH;
    //任务内容
    private String RWNR;
    //任务条码
    private String TXM;
    //任务时间
    private java.util.Date YZSJ;
    //任务显示时间�?
    private java.util.Date RWXSSJC;
    //任务状�??: 有哪些？
    private String RWZT;
    //任务级别:似乎跟任务类型相�?
    private Integer RWJB;
    //任务停止flag(状�?�标�?)
    private Boolean RRTZ;
    //执行�?
    private String ZZR;
    //执行时间
    private java.util.Date ZZSJ;
    //执行结果
    private String ZZJG;
    //审核�?
    private String SHR;
    //审核时间
    private java.util.Date SHSJ;
    //审核结果
    private String SHJG;
    //病人姓名
    private String BRXM;
    //病人性别
    private String BRXB;
    //病人年龄
    private Integer BRNL;
    //提交状�??  0：未提交�? 1:已提�?
    private Integer TJZT;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient TaskDao myDao;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Task() {
    }

    public Task(Long id) {
        this.id = id;
    }

    @Generated
    public Task(Long id, Long BQID, Long USERID, Integer RWLX, String RWM, String ZYH, String RWNR, String TXM, java.util.Date YZSJ, java.util.Date RWXSSJC, String RWZT, Integer RWJB, Boolean RRTZ, String ZZR, java.util.Date ZZSJ, String ZZJG, String SHR, java.util.Date SHSJ, String SHJG, String BRXM, String BRXB, Integer BRNL, Integer TJZT) {
        this.id = id;
        this.BQID = BQID;
        this.USERID = USERID;
        this.RWLX = RWLX;
        this.RWM = RWM;
        this.ZYH = ZYH;
        this.RWNR = RWNR;
        this.TXM = TXM;
        this.YZSJ = YZSJ;
        this.RWXSSJC = RWXSSJC;
        this.RWZT = RWZT;
        this.RWJB = RWJB;
        this.RRTZ = RRTZ;
        this.ZZR = ZZR;
        this.ZZSJ = ZZSJ;
        this.ZZJG = ZZJG;
        this.SHR = SHR;
        this.SHSJ = SHSJ;
        this.SHJG = SHJG;
        this.BRXM = BRXM;
        this.BRXB = BRXB;
        this.BRNL = BRNL;
        this.TJZT = TJZT;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTaskDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取病区ID
     */
    public Long getBQID() {
        return BQID;
    }

    /**
     * 设置病区ID
     */
    public void setBQID(Long BQID) {
        this.BQID = BQID;
    }

    /**
     * 获取责任护士ID
     */
    public Long getUSERID() {
        return USERID;
    }

    /**
     * 设置责任护士ID
     */
    public void setUSERID(Long USERID) {
        this.USERID = USERID;
    }

    /**
     * 获取任务类型
     */
    public Integer getRWLX() {
        return RWLX;
    }

    /**
     * 设置任务类型
     */
    public void setRWLX(Integer RWLX) {
        this.RWLX = RWLX;
    }

    /**
     * 获取任务�?
     */
    public String getRWM() {
        return RWM;
    }

    /**
     * 设置任务�?
     */
    public void setRWM(String RWM) {
        this.RWM = RWM;
    }

    /**
     * 获取住院�?
     */
    public String getZYH() {
        return ZYH;
    }

    /**
     * 设置住院�?
     */
    public void setZYH(String ZYH) {
        this.ZYH = ZYH;
    }

    /**
     * 获取任务内容
     */
    public String getRWNR() {
        return RWNR;
    }

    /**
     * 设置任务内容
     */
    public void setRWNR(String RWNR) {
        this.RWNR = RWNR;
    }

    /**
     * 获取任务条码
     */
    public String getTXM() {
        return TXM;
    }

    /**
     * 设置任务条码
     */
    public void setTXM(String TXM) {
        this.TXM = TXM;
    }

    /**
     * 获取任务时间
     */
    public java.util.Date getYZSJ() {
        return YZSJ;
    }

    /**
     * 设置任务时间
     */
    public void setYZSJ(java.util.Date YZSJ) {
        this.YZSJ = YZSJ;
    }

    /**
     * 获取任务显示时间�?
     */
    public java.util.Date getRWXSSJC() {
        return RWXSSJC;
    }

    /**
     * 设置任务显示时间�?
     */
    public void setRWXSSJC(java.util.Date RWXSSJC) {
        this.RWXSSJC = RWXSSJC;
    }

    /**
     * 获取任务状�??
     */
    public String getRWZT() {
        return RWZT;
    }

    /**
     * 设置任务状�??
     */
    public void setRWZT(String RWZT) {
        this.RWZT = RWZT;
    }

    /**
     * 获取任务级别
     */
    public Integer getRWJB() {
        return RWJB;
    }

    /**
     * 设置任务级别
     */
    public void setRWJB(Integer RWJB) {
        this.RWJB = RWJB;
    }

    /**
     * 获取状�?�标�?
     */
    public Boolean getRRTZ() {
        return RRTZ;
    }

    /**
     * 设置状�?�标�?
     */
    public void setRRTZ(Boolean RRTZ) {
        this.RRTZ = RRTZ;
    }

    /**
     * 获取住院�?
     */
    public String getZZR() {
        return ZZR;
    }

    /**
     * 设置住院�?
     */
    public void setZZR(String ZZR) {
        this.ZZR = ZZR;
    }

    /**
     * 获取执行�?
     */
    public java.util.Date getZZSJ() {
        return ZZSJ;
    }

    /**
     * 设置执行�?
     */
    public void setZZSJ(java.util.Date ZZSJ) {
        this.ZZSJ = ZZSJ;
    }

    /**
     * 获取执行结果
     */
    public String getZZJG() {
        return ZZJG;
    }

    /**
     * 设置执行结果
     */
    public void setZZJG(String ZZJG) {
        this.ZZJG = ZZJG;
    }

    /**
     * 获取审核�?
     */
    public String getSHR() {
        return SHR;
    }

    /**
     * 设置审核�?
     */
    public void setSHR(String SHR) {
        this.SHR = SHR;
    }

    /**
     * 获取审核时间
     */
    public java.util.Date getSHSJ() {
        return SHSJ;
    }

    /**
     * 设置审核时间
     */
    public void setSHSJ(java.util.Date SHSJ) {
        this.SHSJ = SHSJ;
    }

    /**
     * 获取审核结果
     */
    public String getSHJG() {
        return SHJG;
    }

    /**
     * 设置审核结果
     */
    public void setSHJG(String SHJG) {
        this.SHJG = SHJG;
    }

    /**
     * 获取病人姓名
     */
    public String getBRXM() {
        return BRXM;
    }

    /**
     * 设置病人姓名
     */
    public void setBRXM(String BRXM) {
        this.BRXM = BRXM;
    }

    /**
     * 获取病人性别
     */
    public String getBRXB() {
        return BRXB;
    }

    /**
     * 设置病人性别
     */
    public void setBRXB(String BRXB) {
        this.BRXB = BRXB;
    }

    /**
     * 获取病人年龄
     */
    public Integer getBRNL() {
        return BRNL;
    }

    /**
     * 设置病人年龄
     */
    public void setBRNL(Integer BRNL) {
        this.BRNL = BRNL;
    }

    /**
     * 获取提交状�??
     */
    public Integer getTJZT() {
        return TJZT;
    }

    /**
     * 设置提交状�??
     */
    public void setTJZT(Integer TJZT) {
        this.TJZT = TJZT;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
