package wyyy.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import wyyy.bean.Tasks;

import wyyy.dao.TasksDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tasksDaoConfig;

    private final TasksDao tasksDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tasksDaoConfig = daoConfigMap.get(TasksDao.class).clone();
        tasksDaoConfig.initIdentityScope(type);

        tasksDao = new TasksDao(tasksDaoConfig, this);

        registerDao(Tasks.class, tasksDao);
    }
    
    public void clear() {
        tasksDaoConfig.getIdentityScope().clear();
    }

    public TasksDao getTasksDao() {
        return tasksDao;
    }

}
